var search={
  "Activity": "http://fuzzy-sl.squirrel.link/ontology/nonns_Activity.html",
  "Ancient Location": "http://fuzzy-sl.squirrel.link/ontology/AncientLocation",
  "Ancient Region": "http://fuzzy-sl.squirrel.link/ontology/AncientRegion",
  "Archaeological Site": "http://fuzzy-sl.squirrel.link/ontology/ArchaeologicalSite",
  "Bight": "http://fuzzy-sl.squirrel.link/ontology/Bight",
  "Book": "http://fuzzy-sl.squirrel.link/ontology/Book",
  "Campanian Ignimbrite": "http://fuzzy-sl.squirrel.link/ontology/CampanianIgnimbriteProject",
  "Cave": "http://fuzzy-sl.squirrel.link/ontology/Cave",
  "Certainty Type": "http://fuzzy-sl.squirrel.link/ontology/CertaintyType",
  "Coinhoards": "http://fuzzy-sl.squirrel.link/ontology/Coinhoards",
  "Description in Paper": "http://fuzzy-sl.squirrel.link/ontology/PaperDesc",
  "External Repository": "http://fuzzy-sl.squirrel.link/ontology/ExternalRepository",
  "Fuzzy Spatial Locations Ontology": "http://fuzzy-sl.squirrel.link/ontology/",
  "Geological Site": "http://fuzzy-sl.squirrel.link/ontology/GeologicalSite",
  "Georeferencing": "http://fuzzy-sl.squirrel.link/ontology/Georeferencing",
  "Image": "http://fuzzy-sl.squirrel.link/ontology/Image",
  "Island": "http://fuzzy-sl.squirrel.link/ontology/Island",
  "Lake": "http://fuzzy-sl.squirrel.link/ontology/Lake",
  "Location": "http://fuzzy-sl.squirrel.link/ontology/nonns_Location.html",
  "Method Type": "http://fuzzy-sl.squirrel.link/ontology/MethodType",
  "Modern Region": "http://fuzzy-sl.squirrel.link/ontology/ModernRegion",
  "Mountain": "http://fuzzy-sl.squirrel.link/ontology/Mountain",
  "OSM": "http://fuzzy-sl.squirrel.link/ontology/OSM",
  "Person": "http://fuzzy-sl.squirrel.link/ontology/nonns_Person.html",
  "Place": "http://fuzzy-sl.squirrel.link/ontology/Place",
  "Plateau": "http://fuzzy-sl.squirrel.link/ontology/Plateau",
  "Pleiades": "http://fuzzy-sl.squirrel.link/ontology/Pleiades",
  "Project": "http://fuzzy-sl.squirrel.link/ontology/Project",
  "Region Centre": "http://fuzzy-sl.squirrel.link/ontology/RegionCentre",
  "Representative Point": "http://fuzzy-sl.squirrel.link/ontology/RepresentativePoint",
  "River": "http://fuzzy-sl.squirrel.link/ontology/River",
  "Scientific Paper": "http://fuzzy-sl.squirrel.link/ontology/Paper",
  "Silver Coinage of Croton": "http://fuzzy-sl.squirrel.link/ontology/CrotonProject",
  "Sink": "http://fuzzy-sl.squirrel.link/ontology/Sink",
  "Site": "http://fuzzy-sl.squirrel.link/ontology/Site",
  "Site Type": "http://fuzzy-sl.squirrel.link/ontology/SiteType",
  "Source": "http://fuzzy-sl.squirrel.link/ontology/Source",
  "Source Type": "http://fuzzy-sl.squirrel.link/ontology/SourceType",
  "Spatial Object": "http://fuzzy-sl.squirrel.link/ontology/nonns_SpatialObject.html",
  "Spatial Type": "http://fuzzy-sl.squirrel.link/ontology/SpatialType",
  "Supervolcano": "http://fuzzy-sl.squirrel.link/ontology/Supervolcano",
  "Type": "http://fuzzy-sl.squirrel.link/ontology/Type",
  "Unknown Category": "http://fuzzy-sl.squirrel.link/ontology/UnknownCategory",
  "Website": "http://fuzzy-sl.squirrel.link/ontology/Website",
  "Wikimedia Commons": "http://fuzzy-sl.squirrel.link/ontology/WikimediaCommons",
  "activity method description": "http://fuzzy-sl.squirrel.link/ontology/activityDesc",
  "certainty description": "http://fuzzy-sl.squirrel.link/ontology/certaintyDesc",
  "certainty level": "http://fuzzy-sl.squirrel.link/ontology/certaintyLevel",
  "georeferencing done by": "http://fuzzy-sl.squirrel.link/ontology/georeferencingBy",
  "georeferencing method": "http://fuzzy-sl.squirrel.link/ontology/method",
  "has a dubious match": "http://fuzzy-sl.squirrel.link/ontology/dubiousMatch",
  "has a spatial close match": "http://fuzzy-sl.squirrel.link/ontology/spatialCloseMatch",
  "has image": "http://fuzzy-sl.squirrel.link/ontology/image",
  "has partly match": "http://fuzzy-sl.squirrel.link/ontology/partlyMatch",
  "has reference": "http://fuzzy-sl.squirrel.link/ontology/hasReference",
  "has site type": "http://fuzzy-sl.squirrel.link/ontology/siteType",
  "has source": "http://fuzzy-sl.squirrel.link/ontology/hasSource",
  "has source type": "http://fuzzy-sl.squirrel.link/ontology/hasSourceType",
  "has spatial type": "http://fuzzy-sl.squirrel.link/ontology/spatialType",
  "high": "http://fuzzy-sl.squirrel.link/ontology/high",
  "iDAI.gazetter": "http://fuzzy-sl.squirrel.link/ontology/iDAIgazetteer",
  "inhabited Place": "http://fuzzy-sl.squirrel.link/ontology/InhabitedPlace",
  "low": "http://fuzzy-sl.squirrel.link/ontology/low",
  "medium": "http://fuzzy-sl.squirrel.link/ontology/medium",
  "part of": "http://fuzzy-sl.squirrel.link/ontology/partOf",
  "related to": "http://fuzzy-sl.squirrel.link/ontology/relatedTo",
  "representative Geometry": "http://fuzzy-sl.squirrel.link/ontology/representativeGeometry",
  "uncertain": "http://fuzzy-sl.squirrel.link/ontology/uncertain"
}